// AUTO-GENERATED by scripts/generate-static-blog-posts.mjs — do not edit by hand.
import { getLocalBlogPost } from '../../data/localBlogPosts'
import StaticBlogPost from '../../components/StaticBlogPost'

const post = getLocalBlogPost("ait-benhaddou-ouarzazate-guide")!

export default function Page() {
  return <StaticBlogPost post={post} />
}
